const questions=[
{q:'Uma empresa pretende desenvolver um sistema com aplicação Web, API e futuramente aplicações mobile. Sobre a plataforma .NET, analise as afirmações:',c:'I. A plataforma .NET permite desenvolver aplicações Web, APIs, desktop e mobile.\nII. O .NET moderno suporta Windows, Linux e macOS.\nIII. O ASP.NET Core substitui completamente o .NET e é usado exclusivamente para aplicações mobile.',o:['I, apenas.','II, apenas.','I e II, apenas.','II e III, apenas.','I, II e III.'],a:2,e:'A afirmação III é falsa: ASP.NET Core é uma estrutura para aplicações Web, não substitui o .NET nem é exclusiva para mobile.'},
{q:'Um aluno faz login em um sistema acadêmico pelo navegador. O navegador envia os dados ao servidor, que processa a solicitação e retorna uma resposta. Assinale a alternativa correta.',o:['O navegador consulta diretamente o banco de dados, sem o servidor.','O servidor apenas apresenta telas e não realiza processamento.','O cliente envia uma requisição ao servidor, que processa a solicitação e retorna uma resposta.','HTTP é usado somente para armazenar informações no banco.','A arquitetura cliente-servidor elimina a comunicação entre navegador e servidor.'],a:2,e:'Na arquitetura cliente-servidor, o cliente faz a requisição e o servidor processa e devolve a resposta.'},
{q:'Uma API REST precisa consultar todos os clientes, cadastrar um cliente, atualizar o cliente 10 e excluir o cliente 10. Qual conjunto de métodos está correto?',o:['GET /clientes → cadastrar; POST /clientes → consultar; PUT /clientes/10 → excluir; DELETE /clientes/10 → atualizar.','GET /clientes → consultar; POST /clientes → cadastrar; PUT /clientes/10 → atualizar; DELETE /clientes/10 → excluir.','POST /clientes → consultar; GET /clientes → cadastrar; DELETE /clientes/10 → atualizar; PUT /clientes/10 → excluir.','GET /clientes → excluir; POST /clientes → atualizar; PUT /clientes/10 → consultar; DELETE /clientes/10 → cadastrar.','PUT /clientes → consultar; GET /clientes → atualizar; POST /clientes/10 → excluir; DELETE /clientes/10 → cadastrar.'],a:1,e:'Em REST, GET consulta, POST cadastra, PUT atualiza e DELETE exclui.'},
{q:'Uma API recebe GET /produtos e retorna um objeto JSON com id, nome, preco e estoque. Analise:',c:'I. /produtos representa o recurso acessado.\nII. GET indica consulta ou obtenção de informações.\nIII. JSON usa pares de chave e valor.\nIV. JSON é usado exclusivamente por aplicações JavaScript.',o:['I e II, apenas.','II e IV, apenas.','I, II e III, apenas.','I, III e IV, apenas.','I, II, III e IV.'],a:2,e:'JSON é independente de linguagem e pode ser usado por diversas tecnologias; por isso, IV é falsa.'},
{q:'Em um projeto ASP.NET Core, associe cada situação ao componente correto:',c:'Situação 1: classes de entidades como Cliente e Produto.\nSituação 2: receber requisições HTTP e definir a ação.\nSituação 3: comunicação com o banco via Entity Framework Core.\nSituação 4: configuração inicial e serviços.',o:['1 → Controllers; 2 → Models; 3 → Program.cs; 4 → Data.','1 → Models; 2 → Controllers; 3 → Data/DbContext; 4 → Program.cs.','1 → Data; 2 → Models; 3 → Controllers; 4 → appsettings.json.','1 → Program.cs; 2 → Data; 3 → Models; 4 → Controllers.','1 → appsettings.json; 2 → Data; 3 → Program.cs; 4 → Models.'],a:1,e:'Models representam dados, Controllers tratam requisições, Data/DbContext acessa o banco e Program.cs configura a aplicação.'},
{q:'Em uma aplicação ASP.NET Core, a requisição passa por middlewares, roteamento, endpoint/controller e retorna ao cliente. Assinale a correta.',o:['Middleware serve exclusivamente para criar tabelas.','O pipeline HTTP é a sequência de etapas percorridas pela requisição dentro da aplicação.','O Controller sempre é executado antes dos middlewares.','O pipeline HTTP existe somente em aplicações desktop.','Middleware substitui completamente Controllers.'],a:1,e:'O pipeline HTTP organiza a passagem das requisições pelos middlewares e demais componentes.'},
{q:'Sobre appsettings.json e DbContext em uma aplicação ASP.NET Core, assinale a correta.',c:'O appsettings.json pode conter uma seção ConnectionStrings com os dados de acesso ao banco.',o:['appsettings.json recebe requisições e executa Controllers.','DbContext serve somente para criar páginas HTML.','appsettings.json armazena configurações, como strings de conexão, enquanto DbContext comunica-se com o banco.','appsettings.json substitui o banco de dados.','DbContext recebe diretamente as requisições do navegador e substitui HTTP.'],a:2,e:'O arquivo guarda configurações; o DbContext representa a camada de acesso e gerenciamento dos dados.'},
{q:'Para GET /usuarios/10, qual é a sequência mais adequada no processamento de uma requisição HTTP no ASP.NET Core?',o:['Cliente → Endpoint → Middleware → Roteamento → Model Binding → Resposta HTTP.','Cliente → Middleware → Roteamento → Endpoint → Model Binding → Resposta HTTP.','Cliente → Roteamento → Cliente → Middleware → Endpoint → Resposta HTTP.','Cliente → Model Binding → Middleware → Roteamento → Endpoint → Resposta HTTP.','Cliente → Resposta HTTP → Middleware → Roteamento → Endpoint → Model Binding.'],a:1,e:'A requisição entra no pipeline de middlewares, passa pelo roteamento, chega ao endpoint, realiza binding e gera a resposta.'},
{q:'Rotas cadastradas: GET /usuarios, GET /usuarios/{id}, GET /produtos e GET /clientes. Para GET /usuarios/25, qual rota atende?',o:['GET /usuarios, pois o caminho começa com /usuarios.','GET /produtos, pois GET representa consulta.','GET /usuarios/{id}, pois aceita um valor no parâmetro {id}.','O roteamento cria automaticamente /usuarios/25.','Nenhuma, pois {id} deve ser substituído antes da requisição.'],a:2,e:'O segmento 25 corresponde ao parâmetro dinâmico {id} da rota /usuarios/{id}.'},
{q:'Após o roteamento identificar GET /usuarios/{id} para a requisição GET /usuarios/10, o que faz o Model Binding?',o:['Altera a rota /usuarios/{id} para /usuarios/10.','Identifica que 10 foi enviado pelo cliente e o vincula ao parâmetro id.','Cria um endpoint chamado /usuarios/10.','Verifica autorização do usuário.','Escolhe qual rota será utilizada.'],a:1,e:'Model Binding converte e associa valores da requisição aos parâmetros da ação, como id = 10.'},
{q:'Em uma Minimal API foi criado app.MapGet("/usuarios", () => { return new[] { "Ana", "João", "Maria" }; });. Assinale a correta.',o:['Está incorreto: todo endpoint deve estar em um Controller.','MapGet cria um endpoint GET para /usuarios sem necessidade de Controller.','MapGet serve exclusivamente para criar Views HTML.','/usuarios é o nome do Controller criado automaticamente.','Minimal API só deve ser usada com muitos Controllers e regras complexas.'],a:1,e:'Minimal APIs permitem declarar endpoints diretamente, sem a necessidade de Controllers.'},
{q:'No padrão MVC, associe as responsabilidades: I. representar dados de um aluno; II. receber requisição e processar; III. apresentar tela HTML.',o:['I – View; II – Model; III – Controller.','I – Controller; II – View; III – Model.','I – Model; II – Controller; III – View.','I – Model; II – View; III – Controller.','I – View; II – Controller; III – Model.'],a:2,e:'Model representa dados, Controller processa requisições e View apresenta a interface.'},
{q:'Considere var aluno = context.Alunos.Find(1); no Entity Framework Core. Analise:',c:'I. context representa o DbContext.\nII. Alunos é um DbSet que representa entidades Aluno.\nIII. Find(1) procura uma entidade cuja chave primária é 1.\nIV. EF Core exige escrever manualmente um SELECT para cada consulta.',o:['I e II, apenas.','I, II e III, apenas.','II, III e IV, apenas.','I, III e IV, apenas.','I, II, III e IV.'],a:1,e:'I, II e III são verdadeiras. O EF Core pode gerar o SQL a partir das operações do código, então IV é falsa.'},
{q:'Sobre migrations, dados iniciais e conexões no Entity Framework Core, assinale a alternativa correta.',c:'A equipe adicionou Email à classe Aluno, executou Add-Migration AdicionarEmail e Update-Database, usou HasData() e deseja reutilizar conexões.',o:['Add-Migration insere dados iniciais diretamente; HasData cria conexão.','Update-Database cria o Model C#; DbSet atualiza conexões.','Migration registra alterações do Model e pode ser aplicada com Update-Database; HasData define dados iniciais e Connection Pooling reutiliza conexões.','Seed altera apenas estrutura; Migration consulta registros.','Connection Pooling cria uma conexão nova para cada consulta, evitando compartilhamento.'],a:2,e:'Migration versiona mudanças do modelo, Update-Database aplica-as, HasData configura seed e pooling reaproveita conexões.'},
{q:'Em uma View Index.cshtml, o Razor é usado para percorrer Model e gerar <p>@produto.Nome - @produto.Preco</p>. Assinale a correta.',o:['Razor é uma linguagem independente usada para substituir C#.','Razor executa no navegador e transforma C# em HTML no computador do usuário.','Razor permite inserir C# no HTML e gerar páginas dinamicamente no servidor, principalmente nas Views MVC.','Razor acessa diretamente o banco e substitui EF Core.','@ serve somente para comentários em .cshtml.'],a:2,e:'Razor combina marcação HTML com C# no servidor para produzir HTML dinamicamente.'},
{q:'No Dapper, connection.Query<Aluno>("SELECT * FROM Alunos") é executado após abrir uma SqlConnection. Assinale a correta.',o:['Dapper gera automaticamente o SQL a partir de Aluno, sem SELECT.','Query<Aluno>() executa a consulta SQL e transforma os resultados em objetos Aluno.','Dapper substitui o banco e armazena alunos na memória.','connectionString representa a tabela Alunos.','Dapper só consulta o banco por meio do EF Core.'],a:1,e:'Dapper é um micro-ORM que executa o SQL fornecido e mapeia as linhas retornadas para objetos.'},
{q:'Em ADO.NET, uma SqlConnection é aberta e um SqlCommand("SELECT * FROM Alunos", connection) é executado com ExecuteReader(). Assinale a correta.',o:['SqlConnection estabelece a conexão com o banco, enquanto SqlCommand representa o comando SQL executado.','SqlConnection representa a tabela Alunos e SqlCommand cria automaticamente uma tabela.','connectionString contém os dados dos alunos exibidos.','ExecuteReader altera automaticamente dados e não pode ser usado em consultas.','ADO.NET não permite SQL direto; é obrigatório usar EF Core.'],a:0,e:'SqlConnection gerencia a conexão, SqlCommand encapsula o comando e ExecuteReader lê os resultados.'}
];
const letters=['A','B','C','D','E'];let current=0,answers=Array(questions.length).fill(null),seconds=3600,running=true;
const quiz=document.getElementById('quiz');document.getElementById('total').textContent=questions.length;
function render(){quiz.innerHTML=questions.map((x,i)=>`<article class="question ${i===current?'active':''}" data-i="${i}"><div class="q-head"><span class="badge">Questão ${i+1}</span><p class="prompt">${x.q}</p></div>${x.c?`<div class="context">${x.c}</div>`:''}<div class="options">${x.o.map((opt,j)=>`<label class="option ${answers[i]===j?'selected':''}"><input type="radio" name="q${i}" value="${j}" ${answers[i]===j?'checked':''}> <span><strong>${letters[j]})</strong> ${opt}</span></label>`).join('')}</div><div class="nav"><button class="ghost" onclick="go(${i-1})" ${i===0?'disabled':''}>← Anterior</button>${i===questions.length-1?'<button class="primary" onclick="finish()">Finalizar prova</button>':`<button class="primary" onclick="go(${i+1})">Próxima →</button>`}</div></article>`).join('');
quiz.querySelectorAll('input').forEach(input=>input.addEventListener('change',e=>{answers[+e.target.name.slice(1)]=+e.target.value;update()}));document.getElementById('current').textContent=current+1;update();}
function update(){document.getElementById('answered').textContent=answers.filter(x=>x!==null).length;document.querySelectorAll('.option').forEach(x=>{let r=x.querySelector('input');x.classList.toggle('selected',r.checked)});}
function go(i){if(i<0||i>=questions.length)return;current=i;render();window.scrollTo({top:0,behavior:'smooth'})}
function finish(){if(!answers.some(x=>x!==null)||confirm('Finalizar agora? Questões sem resposta serão consideradas erradas.')){clearInterval(clock);document.getElementById('toolbar').classList.add('hidden');quiz.classList.add('hidden');const result=document.getElementById('result');result.classList.add('show');let score=answers.reduce((n,x,i)=>n+(x===questions[i].a?1:0),0);document.getElementById('score').textContent=`${score}/${questions.length} — ${Math.round(score/questions.length*100)}%`;document.getElementById('message').textContent=score>=14?'Excelente! Você está muito bem preparado.':score>=10?'Bom resultado! Revise os pontos indicados abaixo.':'Continue estudando e refaça o simulado após revisar os temas.';document.getElementById('review').innerHTML=questions.map((x,i)=>{let ok=answers[i]===x.a;return `<div class="review-item"><strong>${i+1}. ${ok?'✓ Correta':'✗ Para revisar'}</strong><div class="${ok?'correct':'incorrect'}">Sua resposta: ${answers[i]===null?'não respondida':letters[answers[i]]} · Gabarito: ${letters[x.a]} — ${x.o[x.a]}</div><div class="explain">${x.e}</div></div>`}).join('');window.scrollTo({top:0,behavior:'smooth'})}}
function formatTime(){let m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');document.getElementById('timer').textContent=`Tempo: ${m}:${s}`}
const clock=setInterval(()=>{if(running&&seconds>0){seconds--;formatTime()}else if(seconds===0){running=false;finish()}},1000);
document.getElementById('toggleTimer').onclick=()=>{running=!running;document.getElementById('toggleTimer').textContent=running?'Pausar cronômetro':'Retomar cronômetro'};document.getElementById('finishTop').onclick=finish;document.getElementById('retry').onclick=()=>location.reload();render();
